### ISSUE TITLE
euphoria-beam: consider creating an executor based on apache beam

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#32] opened 2017-02-24 09:49 UTC
It'd be interesting to see an executor, which merely translates a euphoria flow into to the Apache Beam program. Euphoria programs could thus gain the potential to execute on engines supported by Apache Beam. Further, it could show the main differences between the two APIs and potentially uncover conceptual unsoundness in one or the other API.

**Comment by je-ik** [comment] 2017-10-20 13:37
Duplicate of #152

**Closed by je-ik** 2017-10-20 13:37 UTC
Labels: idea
